on:
    issues:
        types: [opened, edited]

jobs:
    autoclose:
        runs-on: ubuntu-latest
        steps:
             - name: Close Issue
               uses: peter-evans/close-issue@v1
               with:
                 comment: |
                     Thanks for reporting an issue! We love feedback.

                     However, this repository is what we call a "subtree split": a read-only copy of one directory of the main repository. It enables developers to depend on specific repository.

                     If you want to report or contribute, you should instead open your issue on the main repository:

                     https://github.com/CrystallizeAPI/boilerplates

                     Thank you for your contribution!
